version: '3.3'
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379 # redis port

  redisadmin:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - 5000:8081 # web interface
    environment:
      REDIS_HOSTS: local:redis:6379
      TZ: America/Recife
    depends_on:
      - redis

  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
      - 5001:4466 # web interface
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: admin
            password: password
            migrations: true
    depends_on:
      - postgres

  postgres:
    image: postgres:10.7-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4:4.5
    restart: always
    ports:
      - 5002:80 # web interface
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
